RF22: RF22AES Class Reference
RF22AES Class Reference
RF22 subclass to enable sending and receiving of encrypted messages.
#include <RF22AES.h>
Public Member Functions
RF22AES (uint8_t thisAddress=0, uint8_t slaveSelectPin=SS, uint8_t interrupt=0)
boolean init ()
uint8_t sendtoWait (uint8_t *buf, uint8_t len, uint8_t dest)
boolean recvfromAck (uint8_t *buf, uint8_t *len, uint8_t *source=NULL, uint8_t *dest=NULL, uint8_t *id=NULL, uint8_t *flags=NULL)
boolean recvfromAckTimeout (uint8_t *buf, uint8_t *len, uint16_t timeout, uint8_t *source=NULL, uint8_t *dest=NULL, uint8_t *id=NULL, uint8_t *flags=NULL)
void setKey (uint8_t *key)
void setIV (uint8_t *iv)
void gen_iv ()
Generate a 128bit IV used for encryption and decryption.
void gen_key ()
Generate a 128bit Key used for encryption and decryption.
boolean sync_iv ()
Synchronize the IV generated by gen_iv with the server.
boolean sync_key ()
Synchronize the Key generated by gen_key with the server.
Public Member Functions inherited from RF22Mesh
RF22Mesh (uint8_t thisAddress=0, uint8_t slaveSelectPin=SS, uint8_t interrupt=0)
boolean init ()
uint8_t sendtoWait (uint8_t *buf, uint8_t len, uint8_t dest)
boolean recvfromAck (uint8_t *buf, uint8_t *len, uint8_t *source=NULL, uint8_t *dest=NULL, uint8_t *id=NULL, uint8_t *flags=NULL)
boolean recvfromAckTimeout (uint8_t *buf, uint8_t *len, uint16_t timeout, uint8_t *source=NULL, uint8_t *dest=NULL, uint8_t *id=NULL, uint8_t *flags=NULL)
uint8_t get_address ()
Get an address from the mesh address server and set the server address.
Public Member Functions inherited from RF22Router
RF22Router (uint8_t thisAddress=0, uint8_t slaveSelectPin=SS, uint8_t interrupt=0)
boolean init ()
void setMaxHops (uint8_t max_hops)
void addRouteTo (uint8_t dest, uint8_t next_hop, uint8_t state=Valid)
RoutingTableEntry * getRouteTo (uint8_t dest)
boolean deleteRouteTo (uint8_t dest)
void retireOldestRoute ()
void clearRoutingTable ()
void printRoutingTable ()
uint8_t sendtoWait (uint8_t *buf, uint8_t len, uint8_t dest)
uint8_t sendtoWait (uint8_t *buf, uint8_t len, uint8_t dest, uint8_t source)
boolean recvfromAck (uint8_t *buf, uint8_t *len, uint8_t *source=NULL, uint8_t *dest=NULL, uint8_t *id=NULL, uint8_t *flags=NULL)
boolean recvfromAckTimeout (uint8_t *buf, uint8_t *len, uint16_t timeout, uint8_t *source=NULL, uint8_t *dest=NULL, uint8_t *id=NULL, uint8_t *flags=NULL)
Public Member Functions inherited from RF22ReliableDatagram
RF22ReliableDatagram (uint8_t thisAddress=0, uint8_t slaveSelectPin=SS, uint8_t interrupt=0)
void setTimeout (uint16_t timeout)
void setRetries (uint8_t retries)
boolean sendtoWait (uint8_t *buf, uint8_t len, uint8_t address)
boolean recvfromAck (uint8_t *buf, uint8_t *len, uint8_t *from=NULL, uint8_t *to=NULL, uint8_t *id=NULL, uint8_t *flags=NULL)
boolean recvfromAckTimeout (uint8_t *buf, uint8_t *len, uint16_t timeout, uint8_t *from=NULL, uint8_t *to=NULL, uint8_t *id=NULL, uint8_t *flags=NULL)
uint16_t retransmissions ()
Public Member Functions inherited from RF22Datagram
RF22Datagram (uint8_t thisAddress=0, uint8_t slaveSelectPin=SS, uint8_t interrupt=0)
boolean init ()
void setThisAddress (uint8_t thisAddress)
boolean sendto (uint8_t *buf, uint8_t len, uint8_t address)
boolean recvfrom (uint8_t *buf, uint8_t *len, uint8_t *from=NULL, uint8_t *to=NULL, uint8_t *id=NULL, uint8_t *flags=NULL)
Public Member Functions inherited from RF22
RF22 (uint8_t slaveSelectPin=SS, uint8_t interrupt=0, GenericSPIClass *spi=&Hardware_spi)
boolean init ()
void reset ()
uint8_t spiRead (uint8_t reg)
void spiWrite (uint8_t reg, uint8_t val)
void spiBurstRead (uint8_t reg, uint8_t *dest, uint8_t len)
void spiBurstWrite (uint8_t reg, const uint8_t *src, uint8_t len)
uint8_t statusRead ()
uint8_t adcRead (uint8_t adcsel=RF22_ADCSEL_INTERNAL_TEMPERATURE_SENSOR, uint8_t adcref=RF22_ADCREF_BANDGAP_VOLTAGE, uint8_t adcgain=0, uint8_t adcoffs=0)
uint8_t temperatureRead (uint8_t tsrange=RF22_TSRANGE_M64_64C, uint8_t tvoffs=0)
uint16_t wutRead ()
void setWutPeriod (uint16_t wtm, uint8_t wtr=0, uint8_t wtd=0)
boolean setFrequency (float centre, float afcPullInRange=0.05)
boolean setFHStepSize (uint8_t fhs)
boolean setFHChannel (uint8_t fhch)
uint8_t rssiRead ()
uint8_t ezmacStatusRead ()
void setMode (uint8_t mode)
void setModeIdle ()
void setModeRx ()
void setModeTx ()
uint8_t mode ()
void setTxPower (uint8_t power)
void setModemRegisters (const ModemConfig *config)
boolean setModemConfig (ModemConfigChoice index)
boolean available ()
void waitAvailable ()
bool waitAvailableTimeout (uint16_t timeout)
boolean recv (uint8_t *buf, uint8_t *len)
boolean send (const uint8_t *data, uint8_t len)
void waitPacketSent ()
bool waitPacketSent (uint16_t timeout)
void setPromiscuous (boolean promiscuous)
uint8_t headerTo ()
uint8_t headerFrom ()
uint8_t headerId ()
uint8_t headerFlags ()
uint8_t lastRssi ()
void setPreambleLength (uint8_t nibbles)
void setSyncWords (const uint8_t *syncWords, uint8_t len)
Additional Inherited Members
Public Types inherited from RF22Mesh
enum message_type {
ADDRESS_REQUEST, SEND_COMMAND_REQ, COMMAND, SEND_COMMAND_RESP,
COMMAND_ACK, SYNC_KEY, SYNC_IV, ADDRESS_GRANT
}
typedef enum RF22Mesh::message_type message_type_t
Static Public Member Functions inherited from RF22
static void printBuffer (const char *prompt, const uint8_t *buf, uint8_t len)
Protected Member Functions inherited from RF22Mesh
virtual void peekAtMessage (RoutedMessage *message, uint8_t messageLen)
virtual uint8_t route (RoutedMessage *message, uint8_t messageLen)
virtual boolean doArp (uint8_t address)
virtual boolean isPhysicalAddress (uint8_t *address, uint8_t addresslen)
void clear_buf (uint8_t *buf, int size)
Static Protected Member Functions inherited from RF22
static void isr0 ()
Low level interrupt service routine for RF22 connected to interrupt 0.
static void isr1 ()
Low level interrupt service routine for RF22 connected to interrupt 1.
static void isr2 ()
Low level interrupt service routine for RF22 connected to interrupt 1.
Protected Attributes inherited from RF22Mesh
uint8_t server_address
Address servers address.
Static Protected Attributes inherited from RF22
static RF22 * _RF22ForInterrupt [] = {0, 0, 0}
Array of instances connected to interrupts 0 and 1.
Detailed Description
RF22 subclass to enable sending and receiving of encrypted messages.
Extends RF22Mesh to add encryption and decryption of messages
Part of the Arduino RF22 library for operating with HopeRF RF22 compatible transceivers (see http://www.hoperf.com)
Constructor & Destructor Documentation
RF22AES::RF22AES (uint8_t thisAddress = 0, uint8_t slaveSelectPin = SS, uint8_t interrupt = 0)
Constructor.
Parameters
[in] key The AES key to use for encryption and decryption
[in] iv the initialization vector used for encryption and decryption
[in] thisAddress The address to assign to this node. Defaults to 0
[in] slaveSelectPin the Arduino pin number of the output to use to select the RF22 before accessing it. Defaults to the normal SS pin for your Arduino (D10 for Diecimila, Uno etc, D53 for Mega)
[in] interrupt The interrupt number to use. Default is interrupt 0 (Arduino input pin 2)
Member Function Documentation
boolean RF22AES::init ()
Initialises this instance and the radio module connected to it. Overrides the init() function in RF22. Internally calls the RF22Mesh::init method
References RF22Datagram::_thisAddress, RF22Mesh::get_address(), and RF22Mesh::init().
boolean RF22AES::recvfromAck (uint8_t * buf, uint8_t * len, uint8_t * source = NULL, uint8_t * dest = NULL, uint8_t * id = NULL, uint8_t * flags = NULL)
Starts the receiver if it is not running already. If there is a valid application layer message available for this node (or RF22_BROADCAST_ADDRESS), send an acknowledgement to the last hop address (blocking until this is complete), then copy the application message payload data to buf and return true else return false. If a message is copied, *len is set to the length.. If from is not NULL, the originator SOURCE address is placed in *source. If to is not NULL, the DEST address is placed in *dest. This might be this nodes address or RF22_BROADCAST_ADDRESS. This is the preferred function for getting messages addressed to this node. If the message is not a broadcast, acknowledge to the sender before returning.
Parameters
[in] buf Location to copy the received message
[in,out] len Available space in buf. Set to the actual number of octets copied.
[in] source If present and not NULL, the referenced uint8_t will be set to the SOURCE address
[in] dest If present and not NULL, the referenced uint8_t will be set to the DEST address
[in] id If present and not NULL, the referenced uint8_t will be set to the ID
[in] flags If present and not NULL, the referenced uint8_t will be set to the FLAGS (not just those addressed to this node).
Returns
true if a valid message was recvived for this node and copied to buf
References RF22Mesh::recvfromAck().
Referenced by recvfromAckTimeout(), sync_iv(), and sync_key().
boolean RF22AES::recvfromAckTimeout (uint8_t * buf, uint8_t * len, uint16_t timeout, uint8_t * source = NULL, uint8_t * dest = NULL, uint8_t * id = NULL, uint8_t * flags = NULL)
Starts the receiver if it is not running already. Similar to recvfromAck(), this will block until either a valid application layer message available for this node or the timeout expires.
Parameters
[in] buf Location to copy the received message
[in,out] len Available space in buf. Set to the actual number of octets copied.
[in] timeout Maximum time to wait in milliseconds
[in] source If present and not NULL, the referenced uint8_t will be set to the SOURCE address
[in] dest If present and not NULL, the referenced uint8_t will be set to the DEST address
[in] id If present and not NULL, the referenced uint8_t will be set to the ID
[in] flags If present and not NULL, the referenced uint8_t will be set to the FLAGS (not just those addressed to this node).
Returns
true if a valid message was copied to buf
References recvfromAck().
uint8_t RF22AES::sendtoWait (uint8_t * buf, uint8_t len, uint8_t dest)
Sends a message to the destination node. Initialises the RF22Router message header (the SOURCE address is set to the address of this node, HOPS to 0) and calls route() which looks up in the routing table the next hop to deliver to. If no route is known, initiates route discovery and waits for a reply. Then sends the message to the next hop Then waits for an acknowledgement from the next hop (but not from the destination node (if that is different).
Parameters
[in] buf The application message data
[in] len Number of octets in the application message data. 0 is permitted
[in] dest The destination node address
Returns
The result code:
RF22_ROUTER_ERROR_NONE Message was routed and deliverd to the next hop (not necessarily to the final dest address)
RF22_ROUTER_ERROR_NO_ROUTE There was no route for dest in the local routing table
RF22_ROUTER_ERROR_UNABLE_TO_DELIVER Noyt able to deliver to the next hop (usually because it dod not acknowledge due to being off the air or out of range
References RF22Mesh::sendtoWait().
Referenced by sync_iv(), and sync_key().
void RF22AES::setIV (uint8_t * iv)
Sets the AES IV (initialization vector)
Parameters
[in] iv the initialization vector used for encryption and decryption
void RF22AES::setKey (uint8_t * key)
Sets the AES key
Parameters
[in] key The AES key to use for encryption and decryption
The documentation for this class was generated from the following files:
RF22AES.h
RF22AES.cpp